### ISSUE TITLE
Chore: no route found for GET /apple-touch-icon.png

### ISSUE THREAD

**Issue by nelsonic** [dwyl/who#172]
Got this debug polluting my terminal: 

```
[info] GET /apple-touch-icon.png
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /apple-touch-icon.png (AppWeb.Router)
    (app 1.7.0) deps/phoenix/lib/phoenix/router.ex:541: AppWeb.Router.call/2
    (app 1.7.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
    (app 1.7.0) deps/plug/lib/plug/debugger.ex:136: AppWeb.Endpoint."call (overridable 3)"/2
    (app 1.7.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
    (phoenix 1.7.12) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (plug_cowboy 2.7.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
    (cowboy 2.12.0) /Users/n/code/who/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.12.0) /Users/n/code/who/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.12.0) /Users/n/code/who/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

# Todo

+ [x] fix it!

**Comment by nelsonic** [comment]
borrowed the file of `icons` from: 
https://github.com/dwyl/mvp/blob/main/lib/app_web/templates/layout/icons.html.heex
included in:
[/lib/app_web/templates/layout/root.html.heex](https://github.com/dwyl/mvp/blob/5c9c10f8ee4ac8aa47b0afc6bcb29b317538df84/lib/app_web/templates/layout/root.html.heex#L20C5-L20C32)
