### ISSUE TITLE
The database for App.Repo couldn't be dropped ... database "app_test" is being accessed by other users

### ISSUE THREAD

**Issue by nelsonic** [dwyl/who#212]
Context: trying to run test from inside `VSCode` 

![image](https://github.com/user-attachments/assets/837b09f3-e5d6-4f4e-98eb-1f3bd44e297c)

```
Mix task exited with reason
an exception was raised:
    ** (Mix.Error) The database for App.Repo couldn't be dropped: ERROR 55006 (object_in_use) database "app_test" is being accessed by other users

There are 10 other sessions using the database.
        (mix 1.17.2) lib/mix.ex:588: Mix.raise/2
        (elixir 1.17.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
        (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
        (mix 1.17.2) lib/mix/task.ex:561: Mix.Task.run_alias/6
        (debug_adapter 0.25.0) lib/debug_adapter/server.ex:2346: ElixirLS.DebugAdapter.Server.launch_task/1
returning code 1
08:50:35.701 [error] Process #PID<0.448.0> raised an exception
** (Mix.Error) The database for App.Repo couldn't be dropped: ERROR 55006 (object_in_use) database "app_test" is being accessed by other users

There are 10 other sessions using the database.
    (mix 1.17.2) lib/mix.ex:588: Mix.raise/2
    (elixir 1.17.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/task.ex:561: Mix.Task.run_alias/6
    (debug_adapter 0.25.0) lib/debug_adapter/server.ex:2346: ElixirLS.DebugAdapter.Server.launch_task/1
```

Would quite like to get this working ... 💭

**Comment by nelsonic** [comment]
Not using `VSCode`. Closing. 📕 
(this is still an issue, just not one I'm going to waste any time trying to fix)
